# Generated by Django 5.2.14 on 2026-05-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("slug", models.SlugField(max_length=550, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("polymarket", "Polymarket"), ("manual", "Manual")],
                        default="polymarket",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("outcomes", models.JSONField(default=list)),
                ("current_probability", models.JSONField(blank=True, default=dict)),
                ("close_date", models.DateTimeField(blank=True, null=True)),
                ("resolution_date", models.DateTimeField(blank=True, null=True)),
                ("resolved_outcome", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
