# Generated by Django 5.2.14 on 2026-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="polymarket_event_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="market",
            name="polymarket_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="market",
            name="polymarket_slug",
            field=models.SlugField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name="market",
            name="polymarket_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
