# Generated by Django 5.2.1 on 2026-05-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_market_polymarket_event_raw_market_polymarket_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="kalshi_event_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="market",
            name="kalshi_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="market",
            name="kalshi_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="market",
            name="kalshi_ticker",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="market",
            name="source",
            field=models.CharField(
                choices=[
                    ("polymarket", "Polymarket"),
                    ("kalshi", "Kalshi"),
                    ("manual", "Manual"),
                ],
                default="polymarket",
                max_length=50,
            ),
        ),
    ]
