# Generated by Django 5.2.1 on 2026-05-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0005_backfill_kalshi_outcome_labels"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="market",
            new_name="markets_mar_status_9d704b_idx",
            old_name="markets_mar_status_8a1f2c_idx",
        ),
    ]
