# Generated by Django 5.2.14 on 2026-05-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0011_market_browse_area_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="accepting_orders",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="market",
            name="game_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
