# Generated by Django 5.2.1 on 2026-06-02 13:26

from django.db import migrations, models


def _payload_metric(*payloads, keys):
    for payload in payloads:
        if not isinstance(payload, dict):
            continue
        for key in keys:
            value = payload.get(key)
            if value is None or value == "":
                continue
            try:
                return float(value)
            except (TypeError, ValueError):
                continue
    return 0.0


def backfill_liquidity_total(apps, schema_editor):
    Market = apps.get_model("markets", "Market")
    batch = []
    for market in Market.objects.only(
        "id",
        "polymarket_raw",
        "polymarket_event_raw",
        "liquidity_total",
    ).iterator(chunk_size=500):
        market.liquidity_total = _payload_metric(
            market.polymarket_raw,
            market.polymarket_event_raw,
            keys=("liquidityNum", "liquidityClob", "liquidity"),
        )
        batch.append(market)
        if len(batch) >= 500:
            Market.objects.bulk_update(batch, ["liquidity_total"])
            batch.clear()
    if batch:
        Market.objects.bulk_update(batch, ["liquidity_total"])


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0014_backfill_world_cup_browse_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="liquidity_total",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.RunPython(backfill_liquidity_total, migrations.RunPython.noop),
    ]
