# Generated by Django 5.2.1 on 2026-05-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0001_initial"),
        ("reputation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularityevent",
            name="pulse_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="popularity_events",
                to="pulse.comment",
            ),
        ),
        migrations.AddField(
            model_name="popularityevent",
            name="pulse_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="popularity_events",
                to="pulse.post",
            ),
        ),
        migrations.AlterField(
            model_name="popularityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("upvote_received", "Upvote received"),
                    ("downvote_received", "Downvote received"),
                    ("comment_posted", "Comment posted"),
                    ("reply_received", "Reply received"),
                    ("post_published", "Post published"),
                ],
                max_length=50,
            ),
        ),
    ]
