# Generated by Django 5.2.1 on 2026-05-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0002_popularityevent_pulse_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="popularityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("upvote_received", "Upvote received"),
                    ("downvote_received", "Downvote received"),
                    ("comment_posted", "Comment posted"),
                    ("reply_received", "Reply received"),
                    ("post_published", "Post published"),
                    ("repost_received", "Repost received"),
                ],
                max_length=50,
            ),
        ),
    ]
