# Generated by Django 5.2.14 on 2026-05-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0004_alter_reputationevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="popularityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("upvote_received", "Upvote received"),
                    ("downvote_received", "Downvote received"),
                    ("comment_posted", "Comment posted"),
                    ("reply_received", "Reply received"),
                    ("post_published", "Post published"),
                    ("repost_received", "Repost received"),
                    ("streak_milestone", "Activity streak milestone"),
                ],
                max_length=50,
            ),
        ),
    ]
