# Generated by Django 5.2.1 on 2026-06-02 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_vote_target_type"),
        ("predictions", "0005_prediction_predictions_status_655aac_idx"),
        ("pulse", "0003_poll"),
        ("reputation", "0005_alter_popularityevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="popularityevent",
            index=models.Index(
                fields=["user", "-created_at"], name="reputation__user_id_664e3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="popularityevent",
            index=models.Index(
                fields=["prediction", "-created_at"],
                name="reputation__predict_0e5744_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="popularityevent",
            index=models.Index(
                fields=["comment", "-created_at"], name="reputation__comment_6d8f34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="popularityevent",
            index=models.Index(
                fields=["pulse_post", "-created_at"],
                name="reputation__pulse_p_3e5c3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reputationevent",
            index=models.Index(
                fields=["user", "-created_at"], name="reputation__user_id_eb7035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reputationevent",
            index=models.Index(
                fields=["prediction", "-created_at"],
                name="reputation__predict_7f4c24_idx",
            ),
        ),
    ]
