# Generated by Django 5.2.1 on 2026-06-12 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0007_reputationevent_unique_prediction_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="popularityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("upvote_received", "Upvote received"),
                    ("downvote_received", "Downvote received"),
                    ("comment_posted", "Comment posted"),
                    ("reply_received", "Reply received"),
                    ("post_published", "Post published"),
                    ("repost_received", "Repost received"),
                    ("streak_milestone", "Activity streak milestone"),
                    ("share_received", "Share received"),
                    ("mission_completed", "Mission completed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SeasonAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=10)),
                (
                    "category_slug",
                    models.SlugField(blank=True, default="", max_length=100),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("reputation_points", models.IntegerField(default=0)),
                ("reputation_score", models.FloatField(default=0)),
                ("scored_forecast_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["season", "category_slug", "rank"],
                "indexes": [
                    models.Index(
                        fields=["season", "category_slug", "rank"],
                        name="reputation__season_e4681b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="reputation__user_id_a56d6e_idx",
                    ),
                ],
                "unique_together": {("user", "season", "category_slug")},
            },
        ),
    ]
