# Generated by Django 5.2 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0010_contestpayoutrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklycontestwinner",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the winner email and login alert were sent.",
                null=True,
            ),
        ),
    ]
