# Generated by Django 5.2.1 on 2026-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0013_contestpayoutrequest_binance_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contestpayoutrequest",
            new_name="reputation__user_id_450b04_idx",
            old_name="reputation__user_id_8a1f0d_idx",
        ),
        migrations.RenameIndex(
            model_name="contestpayoutrequest",
            new_name="reputation__status_a94896_idx",
            old_name="reputation__status_4c2b9e_idx",
        ),
        migrations.RenameIndex(
            model_name="weeklycontestwinner",
            new_name="reputation__week_co_f6faf6_idx",
            old_name="reputation__week_co_6a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="weeklycontestwinner",
            new_name="reputation__user_id_6d22a3_idx",
            old_name="reputation__user_id_7d3e4f_idx",
        ),
        migrations.AlterField(
            model_name="weeklycontestwinner",
            name="prize_usd",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
