# Generated by Django 5.2.15 on 2026-07-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0014_rename_reputation__user_id_8a1f0d_idx_reputation__user_id_450b04_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularityevent',
            name='event_type',
            field=models.CharField(choices=[('upvote_received', 'Upvote received'), ('downvote_received', 'Downvote received'), ('comment_posted', 'Comment posted'), ('reply_received', 'Reply received'), ('post_published', 'Post published'), ('repost_received', 'Repost received'), ('streak_milestone', 'Activity streak milestone'), ('share_received', 'Share received'), ('mission_completed', 'Mission completed'), ('debrief_posted', 'Debrief posted')], max_length=50),
        ),
    ]
