# Generated by Django 5.2.1 on 2026-05-24 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reposted_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposts",
                to="pulse.post",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["reposted_from"], name="pulse_post_reposte_c85f2d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reposted_from__isnull", False)),
                fields=("user", "reposted_from"),
                name="pulse_unique_repost_per_user",
            ),
        ),
    ]
