# Generated by Django 5.2.14 on 2026-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0003_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audience",
            field=models.CharField(
                choices=[("public", "Public"), ("subscribers", "Subscribers only")],
                db_index=True,
                default="public",
                max_length=20,
            ),
        ),
    ]
