# Generated by Django 5.2.1 on 2026-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_prediction_thread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("prediction", "Prediction"),
                    ("pulse_post", "Pulse post"),
                    ("pulse_comment", "Pulse comment"),
                ],
                max_length=20,
            ),
        ),
    ]
