# Generated by Django 5.2.15 on 2026-07-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='target_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('prediction', 'Prediction'), ('pulse_post', 'Pulse post'), ('pulse_comment', 'Pulse comment'), ('debrief', 'Forecast debrief')], max_length=20),
        ),
    ]
