# Generated by Django 5.2.1 on 2026-05-23 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("prediction", "Prediction")], max_length=20
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "target_type"],
                        name="accounts_bo_user_id_d68a1b_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="accounts_bo_target__3a9c66_idx",
                    ),
                ],
                "unique_together": {("user", "target_type", "target_id")},
            },
        ),
    ]
