# Generated by Django 5.2.1 on 2026-05-23 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCategoryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_slug", models.CharField(max_length=50)),
                ("reputation_points", models.IntegerField(default=0)),
                ("popularity_points", models.IntegerField(default=0)),
                ("prediction_count", models.PositiveIntegerField(default=0)),
                ("correct_prediction_count", models.PositiveIntegerField(default=0)),
                ("incorrect_prediction_count", models.PositiveIntegerField(default=0)),
                ("reputation_score", models.FloatField(default=0.0)),
                ("popularity_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User category stats",
                "ordering": ["category_slug"],
                "indexes": [
                    models.Index(
                        fields=["category_slug", "-reputation_score"],
                        name="accounts_us_categor_34f711_idx",
                    ),
                    models.Index(
                        fields=["category_slug", "-popularity_score"],
                        name="accounts_us_categor_729003_idx",
                    ),
                ],
                "unique_together": {("user", "category_slug")},
            },
        ),
    ]
