# Generated by Django 5.2.1 on 2026-05-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_remove_notification_unique_notification_per_prediction_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user_follow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="accounts.userfollow",
            ),
        ),
    ]
