# Generated by Django 5.2.1 on 2026-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_challenge_accepted_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="target_type",
            field=models.CharField(
                choices=[("prediction", "Prediction"), ("pulse_post", "Pulse post")],
                max_length=20,
            ),
        ),
    ]
