# Generated by Django 5.2.14 on 2026-05-28 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                (
                    "risk_notified_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date a 'streak at risk' reminder was sent (dedupe guard).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_active_date"],
                        name="accounts_ac_last_ac_96b9ae_idx",
                    )
                ],
            },
        ),
    ]
