# Generated by Django 5.2.14 on 2026-05-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_activitystreak"),
        ("pulse", "0003_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="pulse_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="pulse.comment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="pulse_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="pulse.post",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_mentions",
            field=models.BooleanField(
                default=True, help_text="Receive alerts when someone @mentions you."
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_replies",
            field=models.BooleanField(
                default=True,
                help_text="Receive alerts when someone replies to your comment.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("followed_user_prediction", "Followed user prediction"),
                    ("new_follower", "New follower"),
                    ("upvote_received", "Upvote received"),
                    ("downvote_received", "Downvote received"),
                    ("prediction_resolved", "Prediction resolved"),
                    ("challenge_invitation", "Challenge invitation"),
                    ("challenge_market_resolved", "Challenge event resolved"),
                    ("challenge_completed", "Challenge completed"),
                    ("challenge_accepted", "Challenge accepted"),
                    ("comment_reply", "Reply to your comment"),
                    ("mention", "You were mentioned"),
                ],
                max_length=40,
            ),
        ),
    ]
