# Generated by Django 5.2.14 on 2026-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0015_notification_pulse_comment_notification_pulse_post_and_more",
        ),
        ("challenges", "0001_initial"),
        ("comments", "0003_alter_vote_target_type"),
        ("markets", "0010_market_spanish_copy"),
        ("predictions", "0004_unique_pending_prediction_per_user_market"),
        ("pulse", "0003_poll"),
        ("reputation", "0005_alter_popularityevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_market_resolving",
            field=models.BooleanField(
                default=True,
                help_text="Receive a reminder when a market you forecast is about to close.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("followed_user_prediction", "Followed user prediction"),
                    ("new_follower", "New follower"),
                    ("upvote_received", "Upvote received"),
                    ("downvote_received", "Downvote received"),
                    ("prediction_resolved", "Prediction resolved"),
                    ("challenge_invitation", "Challenge invitation"),
                    ("challenge_market_resolved", "Challenge event resolved"),
                    ("challenge_completed", "Challenge completed"),
                    ("challenge_accepted", "Challenge accepted"),
                    ("comment_reply", "Reply to your comment"),
                    ("mention", "You were mentioned"),
                    ("market_resolving", "Market resolving soon"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("market__isnull", False), ("notification_type", "market_resolving")
                ),
                fields=("recipient", "notification_type", "market"),
                name="unique_market_resolving_notification",
            ),
        ),
    ]
