# Generated by Django 5.2.14 on 2026-05-28 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_notificationpreference_notify_market_resolving_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["awarded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code"], name="accounts_us_user_id_9cd704_idx"
                    )
                ],
                "unique_together": {("user", "code")},
            },
        ),
    ]
