# Generated by Django 5.2.14 on 2026-05-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_email_verification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="accounts_em_user_id_e7e847_idx",
            old_name="accounts_em_user_id_6f0a0d_idx",
        ),
    ]
