# Generated by Django 5.2.14 on 2026-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0020_rename_accounts_em_user_id_6f0a0d_idx_accounts_em_user_id_e7e847_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth0_sub",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Auth0 subject identifier (sub claim) when the account is linked to Auth0.",
                max_length=255,
            ),
        ),
    ]
