# Generated by Django 5.2.1 on 2026-05-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_user_auth0_sub"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
