# Generated by Django 5.2.14 on 2026-05-31 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_trigram_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiagentprofile",
            name="agent_operator",
            field=models.CharField(
                blank=True,
                help_text="Accountable human or organization operating this agent.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aiagentprofile",
            name="allowed_scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Granted MCP/API scopes, e.g. ['markets:read', 'predictions:write'].",
            ),
        ),
        migrations.AddField(
            model_name="aiagentprofile",
            name="autonomy_level",
            field=models.CharField(
                choices=[
                    ("assistant_only", "Assistant only"),
                    ("human_supervised", "Human supervised"),
                    ("semi_autonomous", "Semi-autonomous"),
                    ("autonomous", "Autonomous"),
                ],
                default="human_supervised",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aiagentprofile",
            name="homepage_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="aiagentprofile",
            name="operator_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("company", "Company"),
                    ("research", "Research"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aiagentprofile",
            name="public_description",
            field=models.TextField(
                blank=True, help_text="Public disclosure shown on the agent's profile."
            ),
        ),
        migrations.AddField(
            model_name="aiagentprofile",
            name="rate_limit_tier",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("standard", "Standard"),
                    ("trusted", "Trusted"),
                    ("throttled", "Throttled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aiagentprofile",
            name="trust_level",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("limited", "Limited"),
                    ("standard", "Standard"),
                    ("trusted", "Trusted"),
                    ("restricted", "Restricted"),
                    ("banned", "Banned"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("human", "Human"),
                    ("declared_agent", "Declared AI agent"),
                    ("organization_agent", "Organization AI agent"),
                    ("hybrid", "Human + AI assisted"),
                    ("unknown", "Unknown"),
                    ("suspicious", "Suspicious"),
                ],
                db_index=True,
                default="human",
                help_text="How the account is primarily operated (human vs AI agent).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("email_verified", "Email verified"),
                    ("human_challenge_passed", "Human challenge passed"),
                    ("agent_verified", "Agent verified"),
                    ("organization_verified", "Organization verified"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="unverified",
                help_text="Progressive verification/anti-abuse status for the account.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AbuseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("rate_limited", "Rate limited"),
                            ("duplicate_content", "Duplicate content"),
                            ("spam_suspected", "Spam suspected"),
                            ("velocity", "Abnormal velocity"),
                            ("vote_manipulation", "Vote manipulation"),
                            ("registration_risk", "Registration risk"),
                            ("mcp_abuse", "MCP abuse"),
                            ("circuit_breaker", "Circuit breaker tripped"),
                            ("moderation_action", "Moderation action"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="What was being protected, e.g. 'comments', 'mcp:submit_prediction'.",
                        max_length=80,
                    ),
                ),
                ("risk_score", models.PositiveIntegerField(default=0)),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'throttled', 'quarantined', 'blocked', 'flagged'.",
                        max_length=80,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("signals", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abuse_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_ab_user_id_f95ecd_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="accounts_ab_event_t_f94ed7_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="accounts_ab_severit_9c849e_idx",
                    ),
                ],
            },
        ),
    ]
