# Generated by Django 5.2.1 on 2026-06-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_backfill_account_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["-reputation_score"], name="accounts_us_reputat_06b003_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["-popularity_score"], name="accounts_us_popular_33a5a2_idx"
            ),
        ),
    ]
