# Generated by Django 5.2.14 on 2026-06-04 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_scored_forecast_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, the user can publish subscriber-only content and accept members.",
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("welcome_message", models.TextField(blank=True)),
                (
                    "monthly_price_cents",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Displayed monthly price in cents (no payment processing in MVP).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_program",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CreatorSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["creator", "status", "-started_at"],
                        name="accounts_cr_creator_aa8c35_idx",
                    ),
                    models.Index(
                        fields=["subscriber", "status"],
                        name="accounts_cr_subscri_1f8e0c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("creator", "subscriber"),
                        name="accounts_unique_creator_subscriber_pair",
                    )
                ],
            },
        ),
    ]
