# Generated by Django 5.2.1 on 2026-06-12 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_backfill_category_exit_stats"),
        ("markets", "0015_market_liquidity_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreak",
            name="freeze_tokens",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Streak freezes available; one is consumed automatically when exactly one day is missed.",
            ),
        ),
        migrations.CreateModel(
            name="MarketWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="markets.market",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_watches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="accounts_ma_user_id_06a567_idx"
                    ),
                    models.Index(
                        fields=["market"], name="accounts_ma_market__1ada18_idx"
                    ),
                ],
                "unique_together": {("user", "market")},
            },
        ),
        migrations.CreateModel(
            name="TopicFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_slug", models.SlugField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="accounts_to_user_id_096423_idx")
                ],
                "unique_together": {("user", "category_slug")},
            },
        ),
        migrations.CreateModel(
            name="UserMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("period_date", models.DateField()),
                ("progress", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "period_date"],
                        name="accounts_us_user_id_44f4ca_idx",
                    )
                ],
                "unique_together": {("user", "code", "period_date")},
            },
        ),
    ]
