# Generated by Django 5.2.15 on 2026-06-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_activitystreak_freeze_tokens_marketwatch_topicfollow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprogram',
            name='monthly_price_cents',
            field=models.PositiveIntegerField(default=500, help_text='Displayed monthly price in cents (no on-platform payment processing).'),
        ),
    ]
