# Generated by Django 5.2.15 on 2026-06-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_creatorprogram_monthly_price_cents'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dm_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_direct_messages',
            field=models.BooleanField(default=True, help_text='Receive alerts when someone sends you a direct message.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('followed_user_prediction', 'Followed user prediction'), ('new_follower', 'New follower'), ('upvote_received', 'Upvote received'), ('downvote_received', 'Downvote received'), ('prediction_resolved', 'Prediction resolved'), ('challenge_invitation', 'Challenge invitation'), ('challenge_market_resolved', 'Challenge event resolved'), ('challenge_completed', 'Challenge completed'), ('challenge_accepted', 'Challenge accepted'), ('comment_reply', 'Reply to your comment'), ('mention', 'You were mentioned'), ('direct_message', 'Direct message'), ('market_resolving', 'Market resolving soon')], max_length=40),
        ),
    ]
