# Generated by Django 5.2.14 on 2026-05-31 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="McpToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label for the token (e.g. 'forecasting-bot-prod').",
                        max_length=120,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="Non-secret identifier shown in UI/logs.",
                        max_length=16,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("rate_limit_tier", models.CharField(default="new", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="McpToolCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="User id when the caller is an agent account (else null).",
                        null=True,
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=120)),
                ("input_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("dry_run", "Dry run"),
                            ("denied", "Denied"),
                            ("error", "Error"),
                            ("rate_limited", "Rate limited"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("risk_score", models.PositiveIntegerField(default=0)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="mcp.mcptoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mcptoken",
            index=models.Index(
                fields=["user", "is_active"], name="mcp_mcptoke_user_id_a53953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcptoolcalllog",
            index=models.Index(
                fields=["tool_name", "-created_at"],
                name="mcp_mcptool_tool_na_004022_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mcptoolcalllog",
            index=models.Index(
                fields=["status", "-created_at"], name="mcp_mcptool_status_0dd6f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcptoolcalllog",
            index=models.Index(
                fields=["user", "-created_at"], name="mcp_mcptool_user_id_ba83c8_idx"
            ),
        ),
    ]
