# Generated by Django 5.2.15 on 2026-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='messaging/attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
