# Generated by Django 5.2.1 on 2026-05-28 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("predictions", "0002_prediction_predicted_direction"),
        ("reputation", "0003_alter_popularityevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttestationSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("prediction_claim", "Prediction claim"),
                            ("prediction_resolution", "Prediction resolution"),
                            ("reputation_event", "Reputation event"),
                            ("profile_summary", "Profile summary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("schema_uid", models.CharField(max_length=66, unique=True)),
                ("schema", models.TextField()),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("chain_id", models.PositiveIntegerField(default=0)),
                ("verifying_contract", models.CharField(blank=True, max_length=66)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "version"),
                        name="unique_attestation_schema_kind_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OffchainAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=66, unique=True)),
                ("signer", models.CharField(max_length=120)),
                ("recipient", models.CharField(blank=True, max_length=120)),
                ("ref_uid", models.CharField(blank=True, max_length=66)),
                ("payload", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(max_length=66)),
                ("signature", models.CharField(max_length=128)),
                (
                    "signature_algorithm",
                    models.CharField(default="proofrep-hmac-sha256", max_length=40),
                ),
                ("raw_attestation", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="verified",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="predictions.prediction",
                    ),
                ),
                (
                    "reputation_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="reputation.reputationevent",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attestations",
                        to="integrations.attestationschema",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attestations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttestationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merkle_root", models.CharField(max_length=66, unique=True)),
                ("transaction_hash", models.CharField(blank=True, max_length=66)),
                ("chain_id", models.PositiveIntegerField(default=0)),
                ("timestamped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attestations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="batches",
                        to="integrations.offchainattestation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="offchainattestation",
            index=models.Index(
                fields=["prediction", "status"], name="integration_predict_bd45a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offchainattestation",
            index=models.Index(
                fields=["reputation_event", "status"],
                name="integration_reputat_6797a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offchainattestation",
            index=models.Index(
                fields=["user", "status"], name="integration_user_id_1161ca_idx"
            ),
        ),
    ]
