# Generated by Django 5.2.14 on 2026-06-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_attestationbatch_daily_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attestationbatch",
            options={"ordering": ["-period_end"]},
        ),
        migrations.AlterField(
            model_name="attestationschema",
            name="kind",
            field=models.CharField(
                choices=[
                    ("prediction_claim", "Prediction claim"),
                    ("prediction_resolution", "Prediction resolution"),
                    ("reputation_event", "Reputation event"),
                    ("profile_summary", "Profile summary"),
                    ("daily_batch_anchor", "Daily batch anchor"),
                ],
                max_length=50,
            ),
        ),
    ]
